spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    schema: classpath:/mysql.sql
zipkin:
   storage:
      type: mysql
server:
  port: 9411
